apiVersion: v1
kind: Service
metadata:
  labels:
    app: liferay
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: database
  
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
        
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liferay
  name: mysql
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_DATABASE
          value: lportal
        - name: MYSQL_USER
          value: liferay
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password1
        image: mysql:5.7.29
        ports:
        - containerPort: 3306
        name: database
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data