apiVersion: v1
kind: Service
metadata:
  labels:
    app: esearch
  name: esearch-cluster
spec:
  ports:
  - port: 9200
  selector:
    app: esearch
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: esearch
  name: esearch-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esearch
  name: esearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: esearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: LCP_PROJECT_ENVIRONMENT
          value: local
        - name: LCP_SERVICE_ID
          value: search
        - name: LCP_SERVICE_SCALE
          value: "1"
        - name: CLUSTER_NAME
          value: liferay-cluster
        - name: HOSTNAME
          value: lr-node1
        image: liferaycloud/elasticsearch:7.9.3-4.1.1
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1"
        ports:
        - containerPort: 9200
        name: esearch
        volumeMounts:
        - mountPath: /lcp-container
          name: esearch-data
      restartPolicy: Always
      volumes:
      - name: esearch-data
        persistentVolumeClaim:
          claimName: esearch-data