apiVersion: v1
kind: Service
metadata:
  labels:
    app: liferay
  name: liferay
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: liferay

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: liferay-portext
data:
  portal-ext.properties: |
    ######### Database ############
    jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver 
    jdbc.default.url=jdbc:mysql://mysql:3306/lportal
    jdbc.default.username=liferay
    jdbc.default.password=password
    ## Company ##
    company.security.auth.type=screenName
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  es.properties: |
    clusterName="liferay-cluster"
    networkHostAddresses=["http://elasticsearch:9200"]
    operationMode="REMOTE"
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liferay
  name: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: liferay
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env: 
        - name: LIFERAY_JAVA_OPTS 
          value: -Xms2g -Xmx2g
        image: liferay/dxp:7.3.10-dxp-2
        resources:
          limits:
            memory: "4098Mi"
            cpu: "2"
        name: liferay 
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/liferay/data
          name: data
        - mountPath: /mnt/liferay
          name: config
        - mountPath: /mnt/liferay/files/portal-ext.properties
          name: portext
          subPath: portal-ext.properties
        - mountPath: /opt/liferay/osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config
          name: elasticsearch
          subPath: com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config
      restartPolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: liferay-data
      - name: config
        persistentVolumeClaim:
          claimName: liferay-config
      - name: portext
        configMap:
          name: liferay-portext
          items:
          - key: "portal-ext.properties"
            path: "portal-ext.properties"
      - name: elasticsearch
        configMap:
          name: es-config
          items:
          - key: "es.properties"
            path: "com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config"